trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: git clone https://github.com/flutter/flutter.git -b beta
  displayName: 'Install Flutter'

- script: ./flutter/bin/flutter doctor
  displayName: 'Flutter Doctor'

- script: ./flutter/bin/flutter test
  displayName: 'Flutter Test'